import «SoftwareFoundations».«LogicalFoundations».«Basics»
import «SoftwareFoundations».«LogicalFoundations».«Induction»
import «SoftwareFoundations».«LogicalFoundations».«Lists»
import «SoftwareFoundations».«LogicalFoundations».«Poly»
import «SoftwareFoundations».«LogicalFoundations».«Tactics»
import «SoftwareFoundations».«LogicalFoundations».«Logic»
import «SoftwareFoundations».«LogicalFoundations».«IndProp»
import «SoftwareFoundations».«LogicalFoundations».«Maps»
import «SoftwareFoundations».«LogicalFoundations».«ProofObjects»
import «SoftwareFoundations».«LogicalFoundations».«IndPrinciples»
