import «Tpil».«DependentTypeTheory»
import «Tpil».«PropositionsAndProofs»
import «Tpil».«QuantifiersAndEquality»
import «Tpil».«Tactics»
import «Tpil».«InteractingWithLean»
import «Tpil».«InductiveTypes»
import «Tpil».«InductionAndRecursion»
import «Tpil».«StructuresAndRecords»
import «Tpil».«TypeClasses»
import «Tpil».«TheConversionTacticMode»
import «Tpil».«AxiomsAndComputation»
